### ISSUE TITLE
create a mapping between Fedora and openSUSE components

### ISSUE THREAD

**Issue by mozeq** [abrt/faf#116]
Opened '20130113T09:02:50' by mtoman as https://fedorahosted.org/abrt/ticket/930

maybe start using storage.Project

**Comment by xsuchy** [comment]
Referenced page does not exists. Additionally this is imho not worth the work. Wontfix. Sorry.

**Comment by jfilak** [comment]
>  Additionally this is imho not worth the work.

Being able to map crashes on Fedora to crashes on openSUSES or any other distribution is worth it because that would allow maintainers join their forces on fixing most common problems. Missing mapping between Fedora components and Debian packages prevents Census Project from using FAF crash stats for calculating the risk score:
https://www.coreinfrastructure.org/programs/census-project
