### ISSUE TITLE
Provide the actual crashing package's version in more discoverable way

### ISSUE THREAD

**Issue by jfilak** [abrt/faf#480]
https://bugzilla.redhat.com/show_bug.cgi?id=1285850

**Comment by laurenolivia** [comment]
@marusak Hello, I am an Outreachy applicant and looking to make my first contribution. Would like to learn more about this issue.

**Comment by marusak** [comment]
Hi,

this issue requests for showing version of the crashing package in the main table on report page. Maybe instead of writing only component name write also the version or also add another row in the table with component version.
Mind that there may be more version affected. I am not sure what would be the best solution. Either show only the newest affected package or write oldest - newest as a range.

**Comment by LucianaMarques** [comment]
Has any PR been done on this? I'd like to contribute!
