### ISSUE TITLE
Private Bugzilla bugs should be ignored

### ISSUE THREAD

**Issue by jfilak** [abrt/faf#527]
Reports with private bugzilla bugs assigned should not be considered as known. Users might want to add their comments or see Status.

**Comment by jfilak** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1377681

**Comment by marusak** [comment]
Hmm, private bug is a relative term. We know groups of each bug (we do not save them yet, but it can be easily done). But how do we find out if the reporting user is in the group? I don't think that is FAF's responsibility. And to say that the report is unknown for each bug in group can cause a lot of duplicity bugs on bugzilla.

I think it would be better if gnome-abrt would recognize if the bugzilla returned is private for the reporting user (since it knows who is reporting) and if so, it would let user to create new one.
Is there something that I am missing? Or do I understand this issue wrongly?

**Comment by jfilak** [comment]
Let's simplify it: a bug is either public i.e. no group assigned or a bug is private - any group.

http://abrt.readthedocs.io/en/latest/faq.html#how-do-i-create-a-private-bugzilla-ticket
https://bugzilla.redhat.com/show_bug.cgi?id=1044653

**Comment by marusak** [comment]
Ok, so you're saying, that if there is at least one group assigned, then create a new bug. Right?

**Comment by jfilak** [comment]
Right.

**Comment by marusak** [comment]
And what about this usecase: I personally am in fedora_contrib group. When I report some bug that has fedora_contrib group, I don't really want to create a new bug.
Won't this create a lot of duplicity bugs?

**Comment by jfilak** [comment]
No, because the Bugzilla report will find the duplicate (in your case) and add a new comment - it will not create a new bug - in 99% of cases, the remaining 1% are bugs.

The KNOWN report feature has been created to simplify the reporting process - just kill the process as soon as possible and do not bother users who are not very interested in reporting crashes - they just want to use their computers for productive work and for reporting bugs. The KNOW report feature isn't there to get rid of duplicate Bugzilla bug reports - that's the responsibility of `report-bugzilla` which searches for duplicates using `Whiteboard = 'abrt_duphas=$UUID'`.

In the case you are not a member of the group, you probably want to have a public bug to see the progress and be notified about fixes.

**Comment by marusak** [comment]
Oh, yeah, you are right.
Thank you for the explaination! 
I'll note here what needs to be done:
1) When pulling bugzillas, pull also groups
2) Save groups into DB (only save True False if there is assigned group)
3) Add condition into reports.py under /new that if there is at least one group known=False
