### ISSUE TITLE
Ignore warn statements when showing crashing function of kerneloops

### ISSUE THREAD

**Issue by mozeq** [abrt/faf#72]
Opened '20121005T09:02:19' by rmarko as https://fedorahosted.org/abrt/ticket/767

Ie, the summary for https://retrace.fedoraproject.org/faf/problems/13955/
should show "function: brcms_c_wait_for_tx_completion".

**Comment by xsuchy** [comment]
Both referenced pages does not exists.

**Comment by jfilak** [comment]
Uff, you have closed so many github issues just because the old issue tracker has been turned off. Frankly, you did a poor job. To clarify the situation around these issues: while migrating the code base from fedorahosted to github, we have also migrated the track tickes - 1 to 1 - the referenced page was just a note.
