### ISSUE TITLE
kernel-core

### ISSUE THREAD

**Issue by RomualdoM** [abrt/faf#998]
kernel 5.15.7-200.fc35.x86_64 in backlight_device_set_brightness.
Msg: "The system encountered a problem and recovered." (?)

**Comment by mgrabovsky** [comment]
Hi, thanks for your message. Unfortunately, it's not clear what the problem is and how it's related to ABRT Analytics.

If you want to report a bug in the Linux kernel or any other software in Fedora, please follow the [_How to file a bug_ guide](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/) over at Fedora Docs.
